import java.io.*;
import java.net.*;
import java.security.*;
import java.util.Base64;
import javax.crypto.*;
import javax.crypto.spec.SecretKeySpec;

//import jdk.javadoc.internal.doclets.formats.html.SourceToHTMLConverter;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();
		DataInputStream in = new DataInputStream(s.getInputStream());
		byte[] enciphered_message = in.readAllBytes();
		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		FileReader file = new FileReader("./secrete_key.txt");
		BufferedReader w = new BufferedReader(file);
		String secrete_key = w.readLine();
		w.close();
		file.close();
		// -Use the key to decrypt the incoming message from socket s.
		byte[] decodedKey = Base64.getDecoder().decode(secrete_key);
		SecretKey originalKey = new SecretKeySpec(decodedKey, 0, decodedKey.length, "DES");
		// -Print out the decrypt String to see if it matches the orignal message.
		Cipher decipher = Cipher.getInstance("DES");
		decipher.init(Cipher.DECRYPT_MODE, originalKey);
		byte[] decipherByte = decipher.doFinal(enciphered_message);
		String decipherText = new String(decipherByte);
		System.out.println(decipherText);
	}
}